parameters:
    rssparameters:
        entity:            
            repository:   tonrepo:entity
            methodName:   derniersItems
        items:
            route:        blog_blog_article
            params:
                id:   id
                slug: 
                    type:   slug
                    target: title
        associations:
            title       : title
            description : description
            pubDate     : createdAt
            guid        : id
        channel:
            title       : title du site
            link        : http://tonsite.fr
            description : Site exemple
            pubDate     :
                type    : datetime
                index   : pubDate
            image       :
                type    : image
                url     : http://www.image.fr/image.jpg
                index   : image
            language      : fr
            copyright     : billyjoue@free.com
            webmaster     : moolwahad@zambie.org
            lastBuildDate :
                type    : datetime
                index   : lastBuildDate
            managingEditor  : richard@free.de (jojo)
            generator       : rudak_generator (patrick)
            ttl             : '10505'

services:
    rss.generator:
        class: Rudak\RssBundle\Classes\RssGenerator
        arguments:
            parameters: %rssparameters% 
            services:
                router      : @router
                templating  : @templating
                doctrine    : @doctrine
