parameters:
#    rudak_rss.example.class: Rudak\RssBundle\Example

services:
#    rudak_rss.example:
#        class: %rudak_rss.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
